"""
Setup script for Bob AI Agent
Automates the installation and configuration process
"""

import subprocess
import sys
import os


def install_requirements():
    """Install Python dependencies."""
    print("📦 Installing Python dependencies...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])
        print("✅ Dependencies installed successfully!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ Error installing dependencies: {e}")
        return False


def download_nltk_data():
    """Download required NLTK data."""
    print("\n📚 Downloading NLTK data...")
    try:
        import nltk
        nltk.download('punkt', quiet=True)
        nltk.download('stopwords', quiet=True)
        print("✅ NLTK data downloaded successfully!")
        return True
    except Exception as e:
        print(f"❌ Error downloading NLTK data: {e}")
        return False


def create_directories():
    """Create necessary directories."""
    print("\n📁 Creating directories...")
    directories = ['uploads', 'outputs', 'samples']
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
    print("✅ Directories created successfully!")
    return True


def check_tesseract():
    """Check if Tesseract OCR is installed."""
    print("\n🔍 Checking for Tesseract OCR...")
    try:
        import pytesseract
        pytesseract.get_tesseract_version()
        print("✅ Tesseract OCR is installed!")
        return True
    except Exception:
        print("⚠️  Tesseract OCR not found!")
        print("\nPlease install Tesseract OCR:")
        print("  Windows: https://github.com/UB-Mannheim/tesseract/wiki")
        print("  macOS: brew install tesseract")
        print("  Linux: sudo apt-get install tesseract-ocr")
        return False


def create_sample_file():
    """Create a sample text file for testing."""
    print("\n📝 Creating sample test file...")
    sample_content = """Introduction to Machine Learning

Machine Learning Overview
Machine learning is a subset of artificial intelligence that enables computers to learn from data without being explicitly programmed. It uses algorithms to identify patterns and make predictions.

Types of Machine Learning
There are three main types of machine learning:

1. Supervised Learning
Supervised learning involves training a model on labeled data. The algorithm learns to map inputs to outputs based on example input-output pairs.

2. Unsupervised Learning
Unsupervised learning finds patterns in unlabeled data. Common techniques include clustering and dimensionality reduction.

3. Reinforcement Learning
Reinforcement learning involves an agent learning to make decisions by interacting with an environment and receiving rewards or penalties.

Key Concepts
- Training Data: The dataset used to train the model
- Features: Input variables used for prediction
- Labels: Output variables in supervised learning
- Model: The mathematical representation learned from data
- Prediction: The output generated by the trained model

Applications
Machine learning has numerous applications including:
- Image recognition and computer vision
- Natural language processing
- Recommendation systems
- Fraud detection
- Autonomous vehicles

Conclusion
Machine learning is transforming industries by enabling computers to learn from data and make intelligent decisions. Understanding the fundamentals is essential for anyone working in data science or AI.
"""
    
    try:
        with open('samples/sample_lecture.txt', 'w', encoding='utf-8') as f:
            f.write(sample_content)
        print("✅ Sample file created: samples/sample_lecture.txt")
        return True
    except Exception as e:
        print(f"❌ Error creating sample file: {e}")
        return False


def main():
    """Main setup function."""
    print("=" * 60)
    print("🤖 Bob AI Agent - Setup Script")
    print("=" * 60)
    
    success = True
    
    # Install requirements
    if not install_requirements():
        success = False
    
    # Download NLTK data
    if not download_nltk_data():
        success = False
    
    # Create directories
    if not create_directories():
        success = False
    
    # Check Tesseract
    tesseract_ok = check_tesseract()
    
    # Create sample file
    if not create_sample_file():
        success = False
    
    print("\n" + "=" * 60)
    if success and tesseract_ok:
        print("✅ Setup completed successfully!")
        print("\n🚀 You can now run the application:")
        print("   streamlit run app.py")
        print("\n📝 Test with the sample file:")
        print("   python bob_agent.py samples/sample_lecture.txt")
    elif success:
        print("⚠️  Setup completed with warnings!")
        print("   Please install Tesseract OCR for image processing.")
        print("\n🚀 You can still run the application:")
        print("   streamlit run app.py")
    else:
        print("❌ Setup encountered errors!")
        print("   Please check the error messages above.")
    print("=" * 60)


if __name__ == "__main__":
    main()

# Made with Bob
